name: JSP Servlet Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java Version
        run: |
          java -version

      - name: Clean Build Directory
        run: |
          rm -rf build
          mkdir -p build/WEB-INF/classes

      - name: Compile Servlet
        run: |
          LIB_PATH=$(find src/main/webapp/WEB-INF/lib -name "*.jar" | tr '\n' ':')

          javac \
          -encoding UTF-8 \
          -cp "${LIB_PATH}:/home/sist/apache-tomcat-11.0.23/lib/servlet-api.jar" \
          -d build/WEB-INF/classes \
          $(find src/main/java -name "*.java")

      - name: Copy Web Application
        run: |
          # JSP, WEB-INF 등 웹 리소스 복사
          cp -r src/main/webapp/* build/

          # 설정 파일 복사 (MyBatis, DB 설정)
          if [ -d "src/main/resources" ]; then
            cp -r src/main/resources/* build/WEB-INF/classes/
          fi

      - name: Create WAR
        run: |
          cd build
          jar -cvf ../JSPLastProject.war .

      - name: Check WAR Contents
        run: |
          jar tf JSPLastProject.war | grep -E "config|properties|class"

      - name: Stop Tomcat
        run: |
          /home/sist/apache-tomcat-11.0.23/bin/shutdown.sh || true
          sleep 5

      - name: Deploy WAR
        run: |
          cp JSPLastProject.war \
          /home/sist/apache-tomcat-11.0.23/webapps/

      - name: Start Tomcat
        run: |
          /home/sist/apache-tomcat-11.0.23/bin/startup.sh
